Add user prefix to s3backend
neicnordic/LocalEGA pull request #19
Opened 2019-12-13 10:39 UTC by viklund

Now it should be possible to have multiple users in the same bucket but
with different roots.

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:
Previously the ingest assumed that the files in inbox was in one bucket per user if the s3 backend was used for the inbox. Now it assumes that all users use the same bucket.

### Changes made:

### Related issues:

### Additional information:

### Release note:

### Documentation change:

### Mentions:

2019-12-13 16:25 UTC, jbygdell requested changes

2019-12-13 16:25 UTC, jbygdell commented on lega/utils/storage.py
> +            location = self.prefix + '/' + location
This has already been added in the `exists` block

2019-12-16 07:18 UTC, jbygdell approved these changes

2019-12-16 07:23 UTC, blankdots approved these changes
LGTM, we will however we need to think of this logic a bit more for future versions.

2019-12-16 07:24 UTC, merged