Featuer/apache mina
neicnordic/LocalEGA pull request #37
Opened 2020-04-08 20:26 UTC by blankdots

### Describe the pull request:

- [ ] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

### Changes made:

### Related issues:

### Additional information:

### Release note:

### Documentation change:

### Mentions:

2020-04-14 08:35 UTC, jbygdell requested changes

2020-04-14 08:35 UTC, jbygdell commented on deploy/bootstrap/url_encode.py
> +#     data = {}
We shouldn't keep commented out code.

2020-04-14 10:47 UTC, jbygdell approved these changes

2020-04-15 07:59 UTC, viklund approved these changes
Maybe request changes?

2020-04-15 07:59 UTC, viklund commented on tests/_common/users.py
> +import asyncio
This import seems unused (asyncio)?

```suggestion
```

2020-04-15 08:39 UTC, merged