Don't sanitize username in ingestion
neicnordic/LocalEGA pull request #44
Opened 2020-05-16 14:58 UTC by dtitov

### Describe the pull request:

- [x] Bug fix
- [ ] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:
Fixes #43

2020-05-17 21:30 UTC, blankdots requested changes
should also be removed from: https://github.com/neicnordic/LocalEGA/blob/master/lega/utils/__init__.py#L18-L20

2020-05-17 23:40 UTC, dtitov commented
I was thinking about keeping it just in case, but sure, we can remove it.

2020-05-18 06:12 UTC, blankdots commented
we can undo changes so keeping code clean is ok.

2020-05-18 06:13 UTC, blankdots approved these changes

2020-05-18 06:14 UTC, merged