Adhere to current messaging schema
neicnordic/LocalEGA pull request #54
Opened 2020-06-23 13:02 UTC by jonandernovella

### Describe the pull request:

- [ ] Bug fix
- [x] Functional change
- [ ] New feature
- [ ] Code cleanup
- [ ] Build system change
- [ ] Documentation change
- [ ] Language translation

### Pull request long description:

The message format of the messages from CEGA has changed so we modified verified and finalize to comply with them
### Changes made:

1) Set stable id now uses decrypted checksums
2) Finalize message schema was updated
3) Verify now talks to the verified shovel

2020-06-24 09:50 UTC, dtitov approved these changes

2020-06-24 10:25 UTC, dtitov commented
Btw, docs should be updated in accordance with the changes: https://github.com/neicnordic/LocalEGA/blob/master/docs/connection.rst

2020-06-24 11:05 UTC, blankdots requested changes
would like to have the tests at least passing and docs updated

2020-06-25 09:45 UTC, blankdots approved these changes
@jonandernovella  would like at least the sequence diagram update in a different PR

2020-06-25 11:16 UTC, merged