Bugfix/fix message
neicnordic/LocalEGA pull request #55
Opened 2020-06-24 19:35 UTC by blankdots

### Describe the pull request:

- [x] Bug fix

### Pull request long description:

### Changes made:

1. Fix integration tests (moved getting accesion id to python script)
2. fix unit tests

### Related issues:

### Additional information:

### Release note:

### Documentation change:

### Mentions:

2020-06-24 20:12 UTC, dtitov requested changes

2020-06-24 20:12 UTC, dtitov commented on docs/connection.rst
> +| completed       | When files are backed uo           |
```suggestion
| completed       | When files are backed up           |
```

2020-06-24 20:12 UTC, dtitov commented on docs/connection.rst
> +| files.verified        | In case the file is properly ingested                 |
Ingested **and** verified: we call 2 microservices.

2020-06-24 20:20 UTC, dtitov approved these changes

2020-06-25 09:37 UTC, jonandernovella approved these changes

2020-06-25 09:37 UTC, merged